// <auto-generated />
using System;
using Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219191943_AddedPriceAndWamthLevel")]
    partial class AddedPriceAndWamthLevel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Model.FixedAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Garment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Neck")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("WarmthLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Garment", "Material", "Neck", "Fit")
                        .IsUnique();

                    b.ToTable("FixedAttributes");
                });

            modelBuilder.Entity("Api.Model.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ImageGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ImageGroupId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Api.Model.ImageGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ModelHeight")
                        .HasColumnType("int");

                    b.Property<string>("ModelWearingSize")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("VariableAttributeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VariableAttributeId");

                    b.ToTable("ImageGroups");
                });

            modelBuilder.Entity("Api.Model.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("VariableAttributeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VariableAttributeId", "Size")
                        .IsUnique();

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("Api.Model.VariableAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FixedAttributeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FixedAttributeId", "Color")
                        .IsUnique();

                    b.ToTable("VariableAttributes");
                });

            modelBuilder.Entity("Api.Model.Image", b =>
                {
                    b.HasOne("Api.Model.ImageGroup", "ImageGroup")
                        .WithMany("Images")
                        .HasForeignKey("ImageGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageGroup");
                });

            modelBuilder.Entity("Api.Model.ImageGroup", b =>
                {
                    b.HasOne("Api.Model.VariableAttribute", "VariableAttribute")
                        .WithMany("ImageGroups")
                        .HasForeignKey("VariableAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VariableAttribute");
                });

            modelBuilder.Entity("Api.Model.StockItem", b =>
                {
                    b.HasOne("Api.Model.VariableAttribute", "VariableAttribute")
                        .WithMany("StockItems")
                        .HasForeignKey("VariableAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VariableAttribute");
                });

            modelBuilder.Entity("Api.Model.VariableAttribute", b =>
                {
                    b.HasOne("Api.Model.FixedAttribute", "FixedAttribute")
                        .WithMany("VariableAttributes")
                        .HasForeignKey("FixedAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FixedAttribute");
                });

            modelBuilder.Entity("Api.Model.FixedAttribute", b =>
                {
                    b.Navigation("VariableAttributes");
                });

            modelBuilder.Entity("Api.Model.ImageGroup", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Api.Model.VariableAttribute", b =>
                {
                    b.Navigation("ImageGroups");

                    b.Navigation("StockItems");
                });
#pragma warning restore 612, 618
        }
    }
}
